version: "3.4"
services:
  blackbox-api:
    build: 
      context: ./blackbox-api
      args:
        - SSH_PRIVATE_KEY
    container_name: blackbox-api
    environment:
      - PUBLIC_WEB=https://${HOST}
      - REDIS_URL=redis://redis
    ports:
      - 8081:8081
    volumes: 
      - ${VIDEO_PATH}:/app/storage
    depends_on:
      - redis
  blackbox-rpc:
    build: 
      context: ./blackbox-rpc
      args:
        - SSH_PRIVATE_KEY
    container_name: blackbox-rpc
    environment:
      - SMTP_ENABLED
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
      - SMTP_SUBJECT
      - PUBLIC_WEB=https://${HOST}
      - REDIS_URL=redis://redis
    ports:
      - 50051:50051
    volumes: 
      - ${VIDEO_PATH}:/app/storage
    depends_on:
      - redis
  redis:
    container_name: blackbox-redis
    image: redis:6.2.6
    restart: always
    volumes: 
      - ${DATA_PATH}:/var/lib/redis
  #postgres:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: example